#????
server:
  port: 3333

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liu?serveTimezone=GMT%2b8
    username: root
    password: 123456

#classpath??resources???
mybatis:
  mapper-locations: classpath:mapper/*.xml #??mapper??xml??


  #支付宝支付
  alipay:
    appId: 2021000122681014
    appPrivateKey: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQCx0QNochA0GOwrWb4U3jayGd5TOJ0VL4n8I3Ezc6brznDBVTw6D9kl/ByPAcVcUwHpCeatupmHcQySQ7nMAxeEPdq7rOUHr5wJj3Hw65KjQ5CtQauWTNG9zAINupDD9YEeayG8zkWwnW6XUBcrg+LwQ6qPawJNTqyQJq7+G3tSoa1W+cFoHLB5mPuKJ2fkc2/aZaLyzZ4pbvM+zwzuhRj5N+4HR8yIgDozNjqCR6zypxmyIksfLxKN+wJWT8SEG9GnuIaErLETrowFILjJbG7d70YtgRA2sVS6n+ORhxjE0lzlor3xQwg0SMIe8Webd/JElwBB50/rOYSySzYXthWzAgMBAAECggEBAILOonYsKrVYfCvrycQqMAxWsVGBPTU/kn9UR0s1Ud74L8RZgoOn8vNZglzFTb18JtSa/wJgWd7kD/5tKfnlcGBM7GLRbm54Bg6WYph7g5Ts+DosLCDWBBleQUh+LU6qhMCuyNPO3j9toNRZC6JsU/6xmIAGlVvve0xT2Ll/1/nRUekf6YSxTdxbqFGX3oPoE56/Hh9Ctq9YCutyss7Zuq2ntHZljLfDQRTFxa9h5pD4d7p17tNGkInEmggk3lattUyKmeiYQc7bAAIOJ+8fvuHdaoPRtzWnkv1iw3g1dr85wgLLf5qaIGdQWUsg0wgCp9R1eXSuPq4NrhTj7CObCqECgYEA2jJgjU/5X3TyoNQzPHdNX/7FqxACtQQ0gK+qRxOi2pSCxJRW1gV/HTFYS9+l2dUcLwwpwih57TS/D80iJWqlQJMDzTIxIBE5h1YAGQyW/icg7bwB4Z/MCap680ccjHuYxl3P+AGK5LP1HE0At9m1HkX7vjNU2rizYLnxo0IpRnECgYEA0J+oj9eo4DF5WTu2I0LC3Pp/oZNGwCmgXbb/RbjVT6NhJCuZ+VsyC7Ou8mpI4fELc6xL/ZoT+l9/zK6pdr71m79RBsRzPP0vb9hAoJoHSP9WxIxXyB2BTtazvbJ+DURy1s4ZLnqelkOHVlfIf+uH9l7u9F700s+Y0KXkGbiZWGMCgYEAp3vd0vqdPyFkkADyJyqoMNQ95FWQzmOg7VppiM9QxRkT21LF6NglP0I+NVdBVhiX3qEmeItbM7G2KqnZ2QCoQg3W8C3juWqfTvu7bX7Vc9aTFwimJQrkslKyt4RRLKA+n50o4oREmdJshcGxmG268bbkSpXaP11hCxEPorJJPnECgYEAjqF5Vs50sMJiWnWOctED9Jx2gfr01hAfibLBF+PkQoxKr7X3kRmeP43bP/UWWxK3Z6AWXA3pNrXv4/pN9ddch9znAp9wwfO/aNIKbUKhVHDt23av1SsG6uWzATB1KZDwipdhc/t1TPpiHs/pTjuzOudwqzX4X+B6c7vXFRa2EE0CgYEAwJA+LfK9GBtDBx3cclfVBIUbk5G/8R3rHSqpwnUoq559PMLj6dKlCIXu9yqlxMYs+lMeXjbGlSKJgJca57nf4TMBpdc4iaHblARx4z0vTYxzsR8aqcRFU+GZ0OgDsarN4EwngbcP4p43Ho1xW5mfTYHvXeChAv1RQDgchI77DRk=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6AURWc18Xpzg+pGWLlasr2pIq0ko00yw6qINDz4VxXAIg5zRtaMERgB+bYwVIhnl7Od11lQUzgj/U9xTY9g2GBlPYWkwL+jAO492qiFb2qGi003PMRr6FP8K4vzZEy1bKh6qlhBDU/uUqFYu6k2taOFCBQXpDNH5Rw4XbKdVfrTnamAkj334vSDZgnnn+GP701Ik7SaY5fJzLyvgdWTn3U+ML5RtKcKhZzd+3mtCS5KcYkP4XLNhFJp8KAwnwHOPCtZqRX7ngKj5oLy5IB1VVDzD1jrzStdDfy+WkRGc5iQ8pHznCTICtmkU82A9qAqaiTok2X1FMmqK06w7elMYuwIDAQAB
    notifyUrl: http://luizhen-doc.natapp1.cc/alipay/notfy

